spring:
  application:
    name: kcb-interview-app
  datasource:
    url: jdbc:h2:mem:b2c_transactions
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 8080
